include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Disable print warnings for debug logging
    avoid_print: false
    
    # Allow BuildContext across async gaps when properly guarded
    use_build_context_synchronously: false
    
    # Allow private types in public API for test files
    library_private_types_in_public_api: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # Ignore all deprecated member use warnings
    deprecated_member_use: ignore